local Spells = DMW.Enums.Spells

Spells.SHAMAN = {
    Elemental = {
        Abilities = {
            EarthShock = {SpellID = 8042},
            FlameShock = {SpellID = 188389},
            HealingSurge = {SpellID = 8004},
            LavaBurst = {SpellID = 51505},
            LightningBolt = {SpellID = 188196},
            WindShear = {SpellID = 57994},
            CleanseSpirit = {SpellID = 51886},
            Thunderstorm = {SpellID = 51490},
            ChainLightning = {SpellID = 188443},
            EarthElemental = {SpellID = 198103},
            FrostShock = {SpellID = 196840},
            Earthquake = {SpellID = 61882},
            FireElemental = {SpellID = 198067},
            ChainLightning2 = {SpellID = 231722},
            ElementalBlast = {SpellID = 117014},
            TotemMastery = {SpellID = 210643},
            StormElemental = {SpellID = 192249},
            LiquidMagmaTotem = {SpellID = 192222},
            AncestralGuidance = {SpellID = 108281},
            Icefury = {SpellID = 210714},
            Stormkeeper = {SpellID = 191634},
            Ascendance = {SpellID = 114050},
        },
        Buffs = {},
        Debuffs = {},
        Talents = {},
        Traits = {}
    },
    Enhancement = {
        Abilities = {
            Flametongue = {SpellID = 193796},
            LavaLash = {SpellID = 60103},
            LightningBolt = {SpellID = 187837},
            Rockbiter = {SpellID = 193786},
            Stormstrike = {SpellID = 17364},
            WindShear = {SpellID = 57994},
            CleanseSpirit = {SpellID = 51886},
            Windfury = {SpellID = 33757},
            CashLightning = {SpellID = 187874},
            FeralSpirit = {SpellID = 51533},
            EarthElemental = {SpellID = 198103},
            Frostbrand = {SpellID = 196834},
            FeralSpirit2 = {SpellID = 231723},
            HealingSurge2 = {SpellID = 190899},
            LightningShield = {SpellID = 192106},
            TotemMastery = {SpellID = 262395},
            FeralLunge = {SpellID = 196884},
            FuryOfAir = {SpellID = 197211},
            Sundering = {SpellID = 197214},
            EarthSpike = {SpellID = 188089},
            Ascendance = {SpellID = 114051},
        },
        Buffs = {},
        Debuffs = {},
        Talents = {},
        Traits = {}
    },
    Restoration = {
        Abilities = {
            ChainHeal = {SpellID = 1064},
            FlameShock = {SpellID = 188838},
            HealingStreamTotem = {SpellID = 5394},
            LavaBurst = {SpellID = 51505},
            LightningBolt = {SpellID = 403},
            Riptide = {SpellID = 61295},
            UnleashLife = {SpellID = 73685},
            WindShear = {SpellID = 57994},
            PurifySpirit = {SpellID = 77130},
            HealingWave = {SpellID = 77472},
            ChaninLightning = {SpellID = 421},
            EarthElemental = {SpellID = 198103},
            Riptide2 =  {SpellID = 231725},
            SpiritwalkerGrace = {SpellID = 79206},
            HealingRain = {SpellID = 73920, CastType = "Ground"},
            ChainHeal2 = {SpellID = 231780},
            SpiritLinkTotem = {SpellID = 98008, CastType = "Ground"},
            HealingTideTotem = {SpellID = 108280},
            --talent
            EarthgrabTotem = {SpellID = 51485},
            EarthenWallTotem = {SpellID = 198838},
            AncestralProtectionTotem = {SpellID = 207399},
            Downpour = {SpellID = 207778},
            CloudburstTotem = {SpellID = 157153},
            Wellspring = {SpellID = 197995},
            Ascendance = {SpellID = 114052},
        },
        Buffs = {
            SpiritwalkerGrace = 79206,
        },
        Debuffs = {
            FlameShock = {SpellID = 188838},
        },
        Talents = {},
        Traits = {}
    },
    --LFGDungeonReadyDialogEnterDungeon
    All = {
        Abilities = {
            AncestralSpirit = {SpellID = 2008},
            EarthbindTotem = {SpellID = 2484, CastType = "Ground"},
            GhostWolf = {SpellID = 2645},
            HealingSurge = {SpellID = 8004},
            CapacitorTotem = {SpellID = 192058, CastType = "Ground"},
            Hex = {SpellID = 51514},
            Bloodlust = {SpellID = 2825},
            AstralShift = {SpellID = 108271},
            TremorTotem = {SpellID = 8143},
            Purge = {SpellID = 370},
            EarthShield = {SpellID = 974},
            WindRushTotem = {SpellID = 192077},
        },
        Buffs = {
            EarthShield = 974,
            GhostWolf = 2645,
        },
        Debuffs = {}
    }
}
